<?php
require dirname(__DIR__) . '/_inc/site.php';
page_head('Impressum & Datenschutzerklärung');
site_header();
?>
<main>
<?php site_hero(); ?>
<section class="section"><div class="container legal">
<h2 class="legal-main-title">Impressum &amp; Datenschutzerklärung</h2>
<p>Der Schutz Ihrer Privatsphäre bei der Verarbeitung persönlicher Daten ist für uns ein wichtiges Anliegen. Wir erheben, verarbeiten und nutzen Ihre persönlichen Daten ausschließlich in Übereinstimmung mit den nachfolgend beschriebenen Grundsätzen und unter Beachtung der anwendbaren Datenschutzgesetze.</p>
<h2>VERANTWORTLICHER</h2><p>Tennisschule Alex Braun<br>Alexander Braun (Geschäftsführer)<br>Heilwigstraße 11a<br>81825 München<br>Tel.: +49 172 2104 303<br>E-Mail: <a href="mailto:info@tennisschule-alexbraun.de">info@tennisschule-alexbraun.de</a></p>
<h2>ARTEN DER VERARBEITETEN DATEN</h2><p>Beim Aufrufen der Website https://tennisschule-alexbraun.de werden durch den auf Ihrem Endgerät zum Einsatz kommenden Browser automatisch Informationen an den Server unserer Website gesendet. Diese Informationen werden temporär in einem sog. Logfile gespeichert. Folgende Informationen werden dabei ohne Ihr Zutun erfasst und bis zur automatisierten Löschung entsprechend den anwendbaren datenschutzrechtlichen Vorschriften gespeichert:</p>
<p>IP-Adresse des anfragenden Rechners,<br>Datum und Uhrzeit des Zugriffs,<br>Name und URL der abgerufenen Datei,<br>Website, von der aus der Zugriff erfolgt (Referrer-URL),<br>verwendeter Browser und ggf. das Betriebssystem Ihres Rechners sowie der Name Ihres Access-Providers.</p>
<p>Die genannten Daten werden durch uns zu folgenden Zwecken verarbeitet:<br>Gewährleistung eines reibungslosen Verbindungsaufbaus der Website, Gewährleistung einer komfortablen Nutzung unserer Website,<br>Auswertung der Systemsicherheit und -stabilität sowie<br>zu weiteren administrativen Zwecken. Die Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 lit. f DSGVO.</p>
<p>Unser berechtigtes Interesse folgt aus oben aufgelisteten Zwecken zur Datenerhebung. In keinem Fall verwenden wir die erhobenen Daten zu dem Zweck, Rückschlüsse auf Ihre Person zu ziehen. Darüber hinaus setzen wir beim Besuch unserer Website Cookies sowie Analysedienste ein. Nähere Erläuterungen dazu erhalten Sie unten.</p>
<h2>WEITERGABE VON DATEN</h2><p>Eine Übermittlung Ihrer persönlichen Daten an Dritte zu anderen als den im Folgenden aufgeführten Zwecken findet nicht statt. Wir geben Ihre persönlichen Daten nur an Dritte weiter, wenn:</p>
<p>Sie Ihre nach Art. 6 Abs. 1 lit. a DSGVO ausdrückliche Einwilligung dazu erteilt haben,<br>die Weitergabe nach Art. 6 Abs. 1 lit. f DSGVO zur Wahrung unserer berechtigten Interessen oder der berechtigten Interessen eines Dritten erforderlich ist und kein Grund zur Annahme besteht, dass Sie ein überwiegendes schutzwürdiges Interesse an der Nichtweitergabe Ihrer Daten haben,<br>für den Fall, dass für die Weitergabe nach Art. 6 Abs. 1 lit. c DSGVO eine gesetzliche Verpflichtung besteht, sowie<br>dies gesetzlich zulässig und nach Art. 6 Abs. 1 lit. b DSGVO für die Abwicklung von Vertragsverhältnissen mit Ihnen erforderlich ist.</p>
<h2>FOTOHINWEIS VERANSTALTUNGEN</h2><p>Während der Veranstaltung werden Foto- und Filmaufnahmen gemacht und diese Aufnahmen im Zusammenhang mit der Veranstaltung für die Öffentlichkeitsarbeit und die Dokumentation, analog und digital, verwendet. Veröffentlicht werden die Bilder auf der Homepage der Tennisschule Alex Braun. Die Aufnahmen werden nur bei Widerruf gelöscht.</p>
<h2>BETROFFENENRECHTE</h2><p>Sie haben das Recht:<br>gemäß Art. 15 DSGVO Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen;<br>gemäß Art. 16 DSGVO unverzüglich die Berichtigung unrichtiger oder Vervollständigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;<br>gemäß Art. 17 DSGVO die Löschung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;<br>gemäß Art. 18 DSGVO die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen;<br>gemäß Art. 20 DSGVO Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesebaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen; und<br>gemäß Art. 77 DSGVO sich bei einer Aufsichtsbehörde zu beschweren. In der Regel können Sie sich hierfür an die Aufsichtsbehörde Ihres üblichen Aufenthaltsortes oder Arbeitsplatzes oder unseres Geschäftssitzes wenden.</p>
<h2>WIDERSPRUCHSRECHT</h2><p>Sofern Ihre personenbezogenen Daten auf Grundlage von berechtigten Interessen gemäß Art. 6 Abs. 1 lit. f DSGVO verarbeitet werden, haben Sie das Recht, gemäß Art. 21 DSGVO Widerspruch gegen die Verarbeitung Ihrer personenbezogenen Daten einzulegen, soweit dafür Gründe vorliegen, die sich aus Ihrer besonderen Situation ergeben oder sich der Widerspruch gegen Direktwerbung richtet. Im letzteren Fall haben Sie ein generelles Widerspruchsrecht, das ohne Angabe einer besonderen Situation von uns umgesetzt wird.</p>
<p>Möchten Sie von Ihrem Widerrufs- oder Widerspruchsrecht Gebrauch machen, genügt eine E-Mail an info@tennisschule-alexbraun.de.</p>
<h2>ÄNDERUNGEN DIESER DATENSCHUTZERKLÄRUNG</h2><p>Diese Datenschutzerklärung ist aktuell gültig. Durch die Weiterentwicklung unserer Website und Angebote darüber oder aufgrund geänderter gesetzlicher beziehungsweise behördlicher Vorgaben kann es notwendig werden, diese Datenschutzerklärung zu ändern. Die jeweils aktuelle Datenschutzerklärung kann jederzeit auf der Website unter Datenschutzerklärung von Ihnen abgerufen und ausgedruckt werden.</p>
</div></section>
</main>
<?php site_footer(); ?>
</body></html>
